build: false

environment:    
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
          PYTHON: "C:\\Python311-x64"

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;C:\Windows\system32;C:\Program Files\CMake\bin
  - pip.exe install conan
  - conan profile detect

test_script:
  # NOTE: This needs Cygwin to be installed in C:\cygwin32
  - conan create .
  - conan cache save omniorb/* --file omniorb_conan_cache.tgz

artifacts:
  - path: omniorb_conan_cache.tgz
    name: omniORB conan cache
